### ISSUE TITLE
Sugestão de mudança do botão adotar

### ISSUE THREAD

**Issue by douglaslimaxx** [HigorSnt/adopt.me#1]
A sugestão é baseada no protótipo. Primeiro que o protótipo está muito bem elaborado, só achei que o botão **adotar** não está levando para o processo de adoção e sim para ver a página de detalhes do animal, eu acho que seria melhor adicionar um botão de **ver detalhes** ou que ao clicarmos no próprio card fossemos redirecionados para essa página de detalhes. O botão de **adotar** deveria levar para o ínicio do processo de adoção.

**Comment by higorsnt** [comment]
muito bem observado, não tinha percebido isso! obrigado :smile:

**Comment by higorsnt** [comment]
acabei optando por remover o botão e o card se tornar clicável... e muito obrigado pelas dicas 🙂
