### ISSUE TITLE
Sugestão para o README

### ISSUE THREAD

**Issue by g1ovanaqueiroz** [HigorSnt/adopt.me#2]
Que projeto massa! Minha sugestão é que teu readme poderia conter também a descrição das funcionalidades do back e telas do front pra ser mais completinho. Mas o projeto tá incrível! :)

**Comment by higorsnt** [comment]
as descrições do backend eu já tinha pensando em adicionar e explicar cada rota direitinho à medida que for sendo implementado, e do front irei adicionar.
muito obrigado! :smile:

**Comment by higorsnt** [comment]
Demorei um pouco para definir todas as telas, mas acabei de fazer isso :sweat_smile:
