### ISSUE TITLE
Sugestão de modularização

### ISSUE THREAD

**Issue by lucasvictor3** [HigorSnt/adopt.me#8]
Boa tarde, só uma sugestão para modularizar essas chamadas para o _backend_, você poderia agrupar todos os _GETs_, _POSTs_ e etc. no arquivo Api.js, dessa forma quando o projeto for expandindo, as chamadas para o servidor irão ficar modularizadas naquele arquivo, podendo referenciar elas através de um _import_ da função ou de uma classe que agrupe todas as chamadas. Só isso mesmo.. Valeeu

https://github.com/HigorSnt/adopt.me/blob/c37e30f463b548bf5770063d0c53aa3aca21eca2/client/src/pages/AdoptableAnimals/index.js#L21

**Comment by higorsnt** [comment]
Obrigado pela dica, e apliquei no projeto.
