### ISSUE TITLE
Transferir lógica de redirecionamento para os itens da lista

### ISSUE THREAD

**Issue by alvesmatheus** [HigorSnt/adopt.me#9]
Oi, @HigorSnt! Queria te sugerir uma alteração no redirecionamento causado pelos cliques em itens da lista de animais adotáveis. Atualmente, quando  os `ListItem` são criados por mapeamento, é necessário encapsulá-los em tags `<Link>` do React Router e essas tags que serão responsáveis por realizar esse redirecionamento, certo?

Você pode utilizar os próprios `ListItem` para fazer o redirecionamento entre rotas, usando o hook `useHistory()` do React Router. Assim, esses componentes precisariam apenas usar esse hook e usar o método `push()` para a rota adequada quando fossem clicados. Naturalmente, essa modificação não altera o funcionamento da tua lista, mas os componentes ficariam mais coesos, já que a lógica dos itens não vai ficar mais distribuída entre os `ListItem` e a página em que eles estão inseridos.

**Comment by higorsnt** [comment]
Obrigado @alvesmatheus , já tinha usado o `useHistory()` e nem lembrava da existência... muito obrigado pela dica!
